# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a750f3ee52b3dadd2eb750152a73bca73b6672502e64d587d8330040649456e9e915e261d52be8eb1a5af9d7fb812ffcac6552eab876dfef1d7513889334a5e

test:
  secret_key_base: 1c8230308cbfa856dd441606c11196779a26ce82b36271b15b4b0098a7651648461bde9b206654af8e64e964e75c4cfe2956e7792a02ea43b03ff7ca51b94539

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
